services:
  portfolio:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: angefolio
    ports:
      - '4321:80'
    restart: unless-stopped
    read_only: true
    security_opt:
      - no-new-privileges:true
    tmpfs:
      - /var/cache/nginx
      - /var/run
    stop_grace_period: 10s
